name: Display Secerts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: ${{ secrets.PROJECT_NAME }} # Reference the secret here
    steps:
      - name: Checkout code ${PROJECT_NAME}"
        uses: actions/checkout@v2
      - name: Use Project Name
        run: echo "Project Name is ${PROJECT_NAME}"
# jobs:
#   display_secret:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Print Slack URL Secret
#         run: echo "SLACK_URL=${{ secrets.SLACK_URL }}"
