# Github actions workflow file
name: Pulumi Destroy Application

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment which you would like to DESTROY. NOTE: This change is permanent!"
        required: true
        type: choice
        options:
          - stg
          - svc
          - prd
      some_other_input:
        description: "Description of your second input"
        required: true
        type: choice
        options: # Adding options for the second input
          - option1
          - option2
          - option3
      another_input:
        description: "Description of your third input"
        required: true
        type: choice # Changed from boolean to choice
        options: # Adding options for the third input
          - choice1
          - choice2
          - choice3

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: ${{ inputs.environment }} # Reference the secret here
      WORKFLOW_RUN_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    steps:
      - name: Checkout code ${PROJECT_NAME}"
        uses: actions/checkout@v2
      - name: Use Project Name
        run: echo "Project Name is ${PROJECT_NAME}"
# jobs:
#   display_secret:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v2

#       - name: Print Slack URL Secret
#         run: echo "SLACK_URL=${{ secrets.SLACK_URL }}"
