name: Display Secerts

on:
  push:
    branches:
      - main

jobs:
  display_secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Slack URL Secret
        run: echo "SLACK_URL=${{ secerts.SLACK_URL }}"
